### PR TITLE
Updated README.md For eventGuru issue#1

### PR DESCRIPTION
**Pull request by MadhurSaluja**
- Added screenshots demonstrating the event creation and event booking flow.
- Updated README to include explanations for each screenshot.
- Refined steps for contributing to the project, including relevant Git commands.
- Enhanced user guidance on how to create and book events on EventGuru.

### CODE REVIEW

**Review by aryad14 — CHANGES_REQUESTED** [review]
Some changes I would like to put light on
1. The project built using NextJS 14
2. In the demo section, the link redirects user to **My Events** page instead of Homepage.
3. The app also uses Clerk for authentication purpose, and stripe for handling payments.
4. In technologies used, include ShadCN, Clerk, Stripe and Uploadthing
5. Steps to contribute should include a step to **Clone** the repository
6. Currently there is no need of including License in the README

Rest looks good to go, only the changes provided above are expected

**Comment by MadhurSaluja** [comment]
@aryad14 All the changes requested are done.

**Review by aryad14 — CHANGES_REQUESTED** [review]
The screenshots you have provided are not visible in the output

**Comment by MadhurSaluja** [comment]
@aryad14 done :)

**Review by aryad14 — APPROVED** [review]
Great Work! Thank you for the contribution

**Pull request merged**
